rxLinePlot(mpg ~ disp, data=mtcars, type="p", xlab="Engine displacement (cu.in)",ylab="Miles per gallon")
rxLinePlot(mpg ~ disp, data=mtcars, type=c("p","r"), xlab="Engine displacement (cu.in)",ylab="Miles per gallon")
rxLinePlot(mpg ~ disp | gear, data = mtcars, type ="p")
rxLinePlot(mpg ~ disp | gear+am, data = mtcars, type ="p")
airlineData<-file.path(rxGetOption("sampleDataDir"),"AirlineDemoSmall.xdf")
rxHistogram(~CRSDepTime, data=airlineData)
rxHistogram(~F(CRSDepTime), data=airlineData)
rxHistogram(~CRSDepTime, data=airlineData, numBreaks = 8)
rxHistogram(~F(CRSDepTime)|DayOfWeek, data=airlineData, xlab="Departure time")
jpeg("testplot.jpg")
rxHistogram(~F(CRSDepTime)|DayOfWeek, data=airlineData, xlab="Departure time")
dev.off()