install.packages("ggplot2")
library(ggplot2)
install.packages("tidyverse")
library(tidyverse)
str(mtcars)
p<-ggplot(data=mtcars)
p+geom_point(mapping=aes(x=disp, y=mpg, color="red"))
mtcars$disp
mtcars$mpg
ggplot(data=mtcars)+geom_bar(mapping=aes(x=gear))
mtcars$gear
ggplot(data=mtcars)+geom_histogram(mapping=aes(x=qsec), binwidth = 2)
p+geom_line(mapping=aes(x=disp, y=mpg))
p+geom_smooth(mapping=aes(x=disp, y=mpg))
p+geom_smooth(mapping=aes(x=disp, y=mpg), method = "lm",formula = y~poly(x,2))
ggplot(mtcars, mapping = aes(x=disp, y=mpg)) + geom_smooth(method = "lm",formula = y~poly(x,2))+geom_point()
ggplot(mtcars, mapping = aes(x=disp, y=mpg,color=factor(am, levels=c(0,1), labels=c("Automatic","Manual"))))+scale_color_manual(values=c("blue","yellow"))+geom_point()+labs(color="Transmission")
ggplot(mtcars, mapping = aes(x=cyl, y=gear, fill=hp))+geom_tile()
ggplot(mtcars)+geom_point(mapping=aes(x=disp, y=mpg))+facet_grid(. ~ am)
ggplot(mtcars)+geom_point(mapping=aes(x=disp, y=mpg))+facet_grid(gear ~ am)
ggplot(mtcars)+geom_point(mapping=aes(x=disp, y=mpg))+facet_wrap( ~ carb, ncol=2)
ggplot(mtcars)+geom_bar(mapping=aes(x=factor(cyl),fill=factor(am)),show.legend = FALSE, position="stack")
mpg_df <- data.frame(name=rownames(mtcars),mpg=mtcars$mpg)
ggplot(mpg_df)+geom_bar(mapping=aes(x=name, y=mpg),stat="Identity")+coord_flip()
library(gridExtra)
