# Generated by Django 2.2.1 on 2019-06-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
                ('month', models.IntegerField(max_length=2)),
                ('day', models.IntegerField(max_length=2)),
                ('hour', models.IntegerField(max_length=2)),
                ('min', models.IntegerField(max_length=2)),
                ('title', models.CharField(max_length=20)),
                ('member', models.IntegerField(max_length=2)),
                ('weight', models.IntegerField(max_length=2)),
                ('start', models.CharField(max_length=10)),
                ('goal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(max_length=10)),
            ],
        ),
    ]
