# Generated by Django 2.2.1 on 2019-06-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bs',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bs',
            name='hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bs',
            name='member',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bs',
            name='min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bs',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bs',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bs',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
